protocol: http://

server:
  host: delivery-borscht.ru
  port: 5000

client:
  host: delivery-borscht.ru
  port: 3000

db:
  nameSql: postgres
  user: delivery
  password: password
  nameDb: delivery_psql
  host: delivery-borscht_postgres
  port: 5432

redis:
  host: delivery-borscht_redis:6379

static:
  folder: static
  default: default

  defaultUserImage: "http://89.208.197.150:5000/default/user/avatar/avatar.png"
  defaultRestaurantImage: "http://89.208.197.150:5000/default/restaurant/restaurant.png"
  defaultDishImage: "http://89.208.197.150:5000/default/dish/dish.png"

microservices:
- auth:
    host: delivery-borscht_auth
    port: 8081

- basket:
    host: delivery-borscht_basket
    port: 8082

- chat:
    host: delivery-borscht_chat
    port: 8083
