name: Test build and deploy Delivery-borscht backend

on:
  push:
    branches: [ dev, master, deploy ]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Run tests with coverage
  #       run: 
  #         go test -coverpkg=./... -coverprofile=cover ./... && cat cover | grep -v "mock" | grep -v  "easyjson" | grep -v "proto" > cover.out &&
  #         go tool cover -func=cover.out

  build:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Main Docker images
        run: 
          sudo docker build -t borschtwithcabbage/delivery-borscht_main:${GITHUB_SHA::8} -f ./docker/main/Dockerfile . &&
          sudo docker tag borschtwithcabbage/delivery-borscht_main:${GITHUB_SHA::8} borschtwithcabbage/delivery-borscht_main:latest

      - name: Build Auth Docker images
        run: 
          sudo docker build -t borschtwithcabbage/delivery-borscht_auth:${GITHUB_SHA::8} -f ./docker/auth/Dockerfile . &&
          sudo docker tag borschtwithcabbage/delivery-borscht_auth:${GITHUB_SHA::8} borschtwithcabbage/delivery-borscht_auth:latest

      - name: Build Basket Docker images
        run: 
          sudo docker build -t borschtwithcabbage/delivery-borscht_basket:${GITHUB_SHA::8} -f ./docker/basket/Dockerfile . &&
          sudo docker tag borschtwithcabbage/delivery-borscht_basket:${GITHUB_SHA::8} borschtwithcabbage/delivery-borscht_basket:latest

      - name: Build Chat Docker images
        run: 
          sudo docker build -t borschtwithcabbage/delivery-borscht_chat:${GITHUB_SHA::8} -f ./docker/chat/Dockerfile . &&
          sudo docker tag borschtwithcabbage/delivery-borscht_chat:${GITHUB_SHA::8} borschtwithcabbage/delivery-borscht_chat:latest

      - name: Push Main Docker images
        run: 
          docker push borschtwithcabbage/delivery-borscht_main:latest &&
          docker push borschtwithcabbage/delivery-borscht_main:${GITHUB_SHA::8}

      - name: Push Auth Docker images
        run: 
          docker push borschtwithcabbage/delivery-borscht_auth:latest &&
          docker push borschtwithcabbage/delivery-borscht_auth:${GITHUB_SHA::8}

      - name: Push Basket Docker images
        run: 
          docker push borschtwithcabbage/delivery-borscht_basket:latest &&
          docker push borschtwithcabbage/delivery-borscht_basket:${GITHUB_SHA::8}

      - name: Push Chat Docker images
        run: 
          docker push borschtwithcabbage/delivery-borscht_chat:latest &&
          docker push borschtwithcabbage/delivery-borscht_chat:${GITHUB_SHA::8}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull All docker images
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: 
            sudo docker pull borschtwithcabbage/delivery-borscht_main:latest &&
            sudo docker pull borschtwithcabbage/delivery-borscht_auth:latest &&
            sudo docker pull borschtwithcabbage/delivery-borscht_basket:latest &&
            sudo docker pull borschtwithcabbage/delivery-borscht_chat:latest
      - name: Deploy docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker rm -f $(sudo docker ps -aq)
            sudo docker run -e VERSION=${GITHUB_SHA::8} -d -p 8080:8080 borschtwithcabbage/delivery-borscht_main:${GITHUB_SHA::8}

      - name: Run backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            export PATH=/snap/bin:$PATH
            cd /home/ubuntu
            docker-compose stop
            docker-compose up -d